### ISSUE TITLE
Can't activate existing account using new login flow (devnet)

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#1009]
I tried connecting to the dashboard using an existing seed phrase on devnet. After hitting the *Activate Account* button, I see the error `Couldn't find a user for the provided mnemonic on dev network.`

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/17682591/c36c8c03-1300-4ad9-b006-7e781f5bdf82)

**Comment by Mahmoud-Emad** [comment]
The problem arose due to the resolution of the issue outlined in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/992. Although the fix for this problem should have been resolved in my local branch, I am currently exploring methods to apply the fix to address the issue mentioned in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/992 as well.

**Comment by Mahmoud-Emad** [comment]
The issue should be fxed in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1031/

**Comment by khaledyoussef24** [comment]
verified on devnet fixed now
[Screencast from 08-24-2023 11:02:42 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/57712e2a-6f97-4d96-b9b7-767ecccf9bf6)
