### ISSUE TITLE
Show powered down nodes as online or standby

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfgrid-sdk-ts#102]
All nodes that are powered down by the farmerbot now show as offline in the dashboard, but these nodes are not really "offline" because they are kept in standby mode. Graphql exposes a powerstate on the node objects which can be queried like:

```
power {
      state
      target
}
```

Let's show nodes with power state: off as standby or online in the dashboard.

(maybe this needs to be added to the gridproxy, I'm not sure)

**Comment by scottyeager** [comment]
This also needs to be addressed somehow in the uptime percentage graph displayed to farmers. That's going to be trickier though, because the uptime for minting purposes depends on knowing the node's historical power state and target, whereas GraphQL only returns current info.

Maybe the best solution here is that the farmerbot can return this info via an RMB call for nodes under management. The dashboard could check for the presence of a running farmerbot on the farmer's twin and adjust its behavior accordingly.

**Comment by Mahmoud-Emad** [comment]
should be updated in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/369

**Comment by mohamedamer453** [comment]
Verified on devnet.

Nodes powered off by the farmerbot now appears as `Standby`.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/623df8b9-df1d-429b-89dc-f21da59df7f1)

And from the description of the `status` parameter in the `nodes` endpoint, standby was also added as a state in the gridproxy.

https://gridproxy.dev.grid.tf/nodes?status=standby

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/0d2c53bb-ecf9-44f6-baf4-8d7363a22dc8)
