### ISSUE TITLE
unclear error message when next cloud deployment fails

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1045]
when the deployment fails unclear error message appears (when there are no public ips are available)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/558ee0ad-7997-43e9-b8c8-d94b84e1e80c)

**Comment by Mik-TF** [comment]
@khaledyoussef24 thanks for creating the issue.

Isn't the last line clearly indicating that there is not enough IP address? "due to error: FarmHasNotEnoughPublicIPsFree"

To be clear: what kind of fix do we want?

1. Publish a clearer error message when there are no public IPs
2. Change the weblet code so that it doesn't let the user deploy on a farm without public IP?

For 2. the weblet should only uses farm with available public IP. Did you use dev net for this test?

Thanks.

**Comment by Mik-TF** [comment]
@khaledyoussef24

Could you tell me the steps you took to (re)generate this error? Thanks!
