### ISSUE TITLE
Dashboard Dedicated Node - Fail to receive GPU information (mainnet verification)

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#1225]
### Description

When using the [Dedicated Nodes GPU filters](https://dashboard.grid.tf/portal/account-nodes), for example with nividia in the GPU vendor name filter, some nodes have the following error:

"Failed to receive node GPUs information"

### Steps to reproduce

* Open the Dedicated Nodes portal: https://dashboard.grid.tf/portal/account-nodes
* Add nividia in GPU vendor
* Open the drop down menu for some nodes
  * Some of them with show the following error
  
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/4abb8015-292b-401d-a1ff-faa145974c5b) 

### Nodes Affected (Sample)

The following nodes had this issue:

* 692
* 697

Perhaps other nodes have the same bug, but I only found those two so far.

### Logs/Alerts

Here's a big screenshot to help troubleshoot.  

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/cd941612-e5d8-48b9-8091-f5e2577fe0b0)

**Comment by A-Harby** [comment]
indeed, both of the mentioned node 692 and 697, failed to receive the GPU info from proxy, request from https://gridproxy.grid.tf/nodes/692/gpu never load.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3391c1be-2ac7-4590-a459-7d508eaa1405)

I have also checked that both have one GPU card, but I noticed that they are not dedicated, and I thought GPU nodes could only be dedicated.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1216dc8c-7667-449a-a60b-e485551bd28f)

**Comment by AhmedHanafy725** [comment]
the issue should be verified once 3.12 reaches mainnet as this issue is most probably in the RMB.

> I have also checked that both have one GPU card, but I noticed that they are not dedicated, and I thought GPU nodes could only be dedicated.

GPU card can be used only if the node is rented. So if the node is free (has 0 contracts), it can be rented and the GPU card can be used, but this might waste the GPU resource on the node as it won't be available for rent if the node has any contracts. It's preferable to make the nodes with GPU cards dedicated to make use of the GPU card.

**Comment by khaledyoussef24** [comment]
blocked on https://github.com/threefoldtech/tfgrid-sdk-go/issues/636

**Comment by zaelgohary** [comment]
Investigations:

Both nodes are down.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/41e46612-d85d-4e08-9419-b0f2513df05f)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/29a03a3a-6678-44f2-aac5-71337230dcd9)

**Comment by khaledyoussef24** [comment]
nodes now seems to be down and with no gpus attached so the issue is no longer producable.


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a5076aa7-390a-47d0-909e-a0eed5c174ad)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5a0587cf-f9dc-4be3-b61a-d50abf408a50)
