### ISSUE TITLE
mass deploy workloads on the grid (mainnet)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1282]
create 1000 (even more the better) workloads randomly on all of the available farms and track the status and in the end cancel all contracts, also reserve ips with care as well

the workflow should be tracked twice daily

**Comment by mohamedamer453** [comment]
Update:

WIP, added a script for mass deployments with randomized resources on random farms and nodes. The script is still missing the logic for tracking the status of the deployments and the workflow logic is ready but is not implemented yet.

#1289

**Comment by zaelgohary** [comment]
@xmonader we search for an available node before deploying and choose one of them randomly.

**Comment by mohamedamer453** [comment]
Update:

- Fixed the script and added the status tracking logic.
- Added the workflow. (Will be further tested and improved once it's merged).

Pr is ready for review #1289

**Comment by A-Harby** [comment]
[Workflow](https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/6701014026/job/18207825733) failed today.

And I also couldn't find a release match `v2.2.0` from worlflow
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d0105439-5391-461a-a149-72c3d3676cc4)

**Comment by mohamedamer453** [comment]
> [Workflow](https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/6701014026/job/18207825733) failed today.
> 
> And I also couldn't find a release match `v2.2.0` from worlflow ![image](https://user-images.githubusercontent.com/109473873/279444542-d0105439-5391-461a-a149-72c3d3676cc4.png)


Yes it's expected to fail since as you mentioned `v2.2.0` doesn't exist yet however it's the next version that's going to be released for mainnet. we currently cannot run it on the current version for mainnet since it won't find the `mass_deployments.ts` script. so it's expected to keep failing until the next version is released. and if you want to verify that it's working [here](https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/6684027673) is a run that was done on dev branch while testing the worflow and it ran without any issues.

**Comment by mohamedamer453** [comment]
> [Workflow](https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/6701014026/job/18207825733) failed today.
> 
> And I also couldn't find a release match `v2.2.0` from worlflow ![image](https://user-images.githubusercontent.com/109473873/279444542-d0105439-5391-461a-a149-72c3d3676cc4.png)

Should be solved in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1334

**Comment by xmonader** [comment]
will close this and keep the other one #1352  for 3.13
