### ISSUE TITLE
Tests are failing in yggdrasil installation

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1303]
check this run https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/6680221000/job/18153127199

**Comment by mohamedamer453** [comment]
Update:

Still investigating the issue and trying to find what's causing the issue, tried to manually install yggdrasil on multiple vms deployed from the grid but it didn't work and it crashed the vms since the vms already had yggdrasil installed and configured. Currently trying to manually install it on local ubuntu image using docker but i'm still facing some issues with the docker images.

**Comment by A-Harby** [comment]
Verified, 
The test workflow ran successfully today, and the yggdrasil was installed with no errors. The yggdrasil was specified to use the 0.4.7 version.

https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/6700526217/job/18206601169
