### ISSUE TITLE
Show notification in case of slow connectivity 

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-ts#1306]

**Comment by mohamedamer453** [comment]
Update:

Work Completed:

- Moved the grid client object inside the try/catch block and now appropriate error messages are displayed when a network error happens. 
- Didn't add a separate notification since already a clear error message appears for the user and the nodes field doesn't infinitely load anymore as seen in #1374 


Status:

Pr is ready for review.

**Comment by A-Harby** [comment]
Verified,
- Devnet
- 6d0ec3d
- [TC2307 - Error message for filter failure](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422336#case_4155955)

I tried with slow and by turning the network offline and the message error was shown to me and the validating stopped loading.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9a814597-4864-4e48-aa1b-1ebc0d675318)

**Comment by ramezsaeed** [comment]
verified:
- Devnet
- 000eea2
