### ISSUE TITLE
check node storage pool invalid error message  

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1341]
We need to handle network errors; any error while validating the storage pool will show the error message: `Couldn't fit the required disks in Node ${validatingNode.nodeId} storage pools, please select another node`

_Originally posted by @0oM4R in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1300#issuecomment-1789402379_

**Comment by mohamedamer453** [comment]
Update:

Investigation and Solution:

- Still investigating the issue, was able to output the error messages that come from the grid client but when i do that the storage pools message gets overridden by the one from the client. 
- Still looking for a solution to output both the network error messages from the client and the desired message for the storage pools.

**Comment by 0oM4R** [comment]
I believe we should wait for this issue [#995](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/995)

**Comment by mohamedamer453** [comment]
Update:

Work Done:

- Added a condition to check for the returned error if it's a storage pools error it'll return a message mentioning that the storage pools are not enough and if it's a network error it'll return an error message mentioning that something went wrong while checking the storage pools.
- Could be improved once #995 is available since the current method checks for a part of the error message.

Status: Pr is ready for review.

**Comment by maayarosama** [comment]
Verified on Devnet
![2024-01-02_11-54](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/587ca19a-568c-4420-92fc-85d15ef6854e)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 228c723
