### ISSUE TITLE
[Mainnet] Playground: Huge number of requests on initialization 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1373]
### Description
huge number of fetch requests most of them to the same endpoint with different page number

[Screencast from 07 نوف, 2023 EET 10:49:34 ص.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/3ee1c1e2-b0e4-4934-8b8f-085c2cb33e77)

### Steps to reproduce
go to https://playground.grid.tf/#/
Log in and check the network tab 
> try to force reload if it is not reproducible.

**Comment by Mahmoud-Emad** [comment]
Currently, retrieving offline nodes involves multiple requests and loops, causing inefficient use of resources and impacting performance. This issue is currently blocked on [tfgrid-sdk-go issue #423](https://github.com/threefoldtech/tfgrid-sdk-go/issues/423). Once resolved, it will enable a more streamlined approach to handling offline nodes.

**Current Behavior:**

1. **Multiple Requests:** The system requests the grid proxy for offline nodes, which returns paginated results. If there are many offline nodes (e.g., 1000), this results in numerous requests (e.g., 20~100 requests) due to pagination.

2. **Array Comparison:** Alternatively, the system loops through node IDs and user contracts to check if the contract's node ID exists in the node IDs array.

**Proposed Solution:**

Once [tfgrid-sdk-go issue #423](https://github.com/threefoldtech/tfgrid-sdk-go/issues/423) is resolved, the system can optimize performance by:

- Making a single request with an array of specific node IDs (e.g., [1, 2, 3, 4, 5]) representing the offline nodes.
- Receiving an array of node objects directly related to the requested node IDs, eliminating the need for multiple requests and loops.

This optimized approach significantly improves performance and reduces unnecessary resource consumption.

**Comment by khaledyoussef24** [comment]
verified
env used : devnet
version : 7f4d8ea
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/40abb15e-3f6b-49e1-8915-fde302682035)

**Comment by Mahmoud-Emad** [comment]
@khaledyoussef24 

Please keep in mind that this issue needs to be re-verified on mainnet.

**Comment by khaledyoussef24** [comment]
also verified on mainnet only two requests were made
![Screenshot from 2024-01-22 13-57-07](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/486c5602-9680-4e6e-86d9-ab9ed7e2c2bb)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6f58c34b-c0b5-4e7c-84d5-2c9b6e605162)
