### ISSUE TITLE
Reset solutions inputs after back button

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1378]
### Description

After deployment is done, the solution inputs should be reset when the back button is pressed.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/65176432-2aa2-4d1a-93fc-bcc52adcc512)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/caacadd9-c190-4bb2-860c-93d5c72bf5b8)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b54b39d2-b0ca-4163-9d6d-8ed88914ef36)

**Comment by MohamedElmdary** [comment]
For this issue we can remount the slot of solution passed in weblet layout however that remounting will cause some components to reset for example (node selector, domainName) but other like (VTextField (name), VSwitch (dedicated)) for example won't reset

but why? 
in case of nodeSelector these are custom components we created which trigger an update event onMount with undefined value as initial value so it resets

but in case of VTextField vuetify won't reset input because what is the point of doing that user might start with initial value

Solution? 
We have some solution (ofc there might be more)
1. Refactor code to use custom components so it reset (too long)
2. expose @success event from weblet layout so we can reset data when it triggers
3. Update VTextField, VSwitch, all vuetify inputs to reset at initial load (and update register in vuetify.ts)

**Comment by MohamedElmdary** [comment]
We should rerender that component after success deployment (when click back)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- d2d2622
