### ISSUE TITLE
Bridge: Learn how links to an outdated documentation

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1485]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/3f026920-2066-4c4d-b1e2-31b5c81a810d)

https://manual.grid.tf/threefold_token/tft_bridges/tfchain_stellar_bridge.html#how-to-use-the-tfchain-stellar-bridge

**Comment by mohamedamer453** [comment]
Update:

Investigation:

This issue is blocked on https://github.com/threefoldtech/info_grid/issues/301 and the documentation issue is also currently blocked since:
- the instances for testnet and mainnet are not available yet 
- the steps can't be updated yet since profile manager extension isn't merged yet so the flow is not finalized yet to document.

**Comment by khaledyoussef24** [comment]
verified and updated on devnet
version : 433ad62
<img width="1680" alt="Screenshot 2024-03-03 at 12 11 25 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/79328e2b-f67e-40ce-8646-58bf3b5366bc">
<img width="233" alt="Screenshot 2024-03-03 at 12 11 33 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/488998f8-8144-43c3-b09c-db7a24bb3414">

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4226598

**Comment by ramezsaeed** [comment]
Verified:
- Testnet
- 2.3.0-rc1
