### ISSUE TITLE
Minting Page: Testing

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1566]
- Title is wrong

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/180bf3bc-b897-476d-9af4-767e0e532f22)

Should say Threefold Grid Minting Explorer

- `All Data Subject To Change` should be in a smaller font with a warning (as a note, not as a heading!)
- What is the receipt hash? what is minting ? How do I get it that receipt hash? all of that is missing
- Make sure to add more information before the form and link to the manual

## Behavior

- Required error message
This is how it looks in the initial state
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/2d8ee4bb-2b66-4f50-9a44-a6aab35d5d99)

As soon as I click on the receipt hash textinput and bring it to focus and click out, this happens
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/1b262460-5921-40ee-8d9c-528bca1fa41f)

- Validity of the hash receipt

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/75ab0c9c-5cda-4dd6-9741-3f0b163fa90a)
any 64 chars makes it 'valid' (reasonable check is trying to fetch the hash immediately or wait until the user click on View to say it's invalid if it doesn't exist

- Shouldn't have not found and invalid messages at the same time 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/46a0a917-1bd7-43fd-b968-284f790ed635)

- surround the the hash with backticks to make it more visible in the error message 

Note: how to get receipt hashes to test against? you can check https://alpha.minting.tfchain.grid.tf/api/v1/node/$NODE_ID e.g `https://alpha.minting.tfchain.grid.tf/api/v1/node/42` 

- Checking against valid hash doesn't work! 

e.g the hash `d7ed579633b8320a130dd84f014db94f519a79596dbb313511516d26aea6371b`

screenshot from the old website 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/928f877d-35d0-43eb-afdb-6f17961914aa)

screenshot from the new minting 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/1de11652-1d6c-4afe-a0c1-34d7e3d28030)

I checked the console it seems it's using a relative path for the API while it should have been using the `alpha.minting.tfchain.grid.tf/` 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/1417ef5b-dc08-4b5f-9dd1-c3cabf96adb0)

I was testing against new.playground.dev.grid.tf

**Comment by zaelgohary** [comment]
Some requirments are not done yet.

[Grid Minting](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4153425)
[Grid Minting Validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4153428)

> * Title is wrong
> * Should say Threefold Grid Minting Explorer
> * `All Data Subject To Change` should be in a smaller font with a warning (as a note, not as a heading!)

- The title is changed and a hint is added.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/3fb6a302-5c81-4453-9ec4-4a37cc1060d4)

> What is the receipt hash? what is minting ? How do I get it that receipt hash? all of that is missing
- A details pop-up is added. However, the manual link redirects to [Farming Rewards](https://manual.grid.tf/faq/faq.html?highlight=receipt%20hash#farming-rewards-and-related-notions) instead of the [Minting Section](https://manual.grid.tf/faq/faq.html?highlight=receipt%20hash#what-is-the-tft-minting-process-is-it-fully-automated)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/9f7d5410-c267-428b-a6d3-0b82f2a2cd16)


> As soon as I click on the receipt hash textinput and bring it to focus and click out, this happens
Validation no longer gets triggered unless I start writing.

- Validation doesn't happen unless I start typing
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/a2b0b112-291a-444d-b79b-606218ce9fe9)

> * Validity of the hash receipt
- Validation works for length only but not for wrong hashes.

Steps to reproduce:
- Add valid hash
- Click on view
- Replace the valid hash with an invalid 46-length hash
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/2db9d7b9-40d4-4329-80f6-39228e830159)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/cce6eeaa-8e06-4a83-b7da-6624a007edf7)


> * Shouldn't have not found and invalid messages at the same time
> * Validity of the hash receipt
> * any 64 chars makes it 'valid' (reasonable check is trying to fetch the hash immediately or wait until the user click on View to say it's invalid if it doesn't exist
> * Shouldn't have not found and invalid messages at the same time
> * surround the the hash with backticks to make it more visible in the error message
> I checked the console it seems it's using a relative path for the API while it should have been using the alpha.minting.tfchain.grid.tf/
- All is done

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/e44a91e9-9613-417a-b669-75d28b248f5a)


> Checking against valid hash doesn't work!
- Not anymore.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/5ca23561-ee4f-48ed-9f9c-7c3a04a01603)
