### ISSUE TITLE
Yggdrasil isn't working

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1584]
### Description

Yggdrasil version 0.5.4, and I used peers from https://github.com/threefoldtech/zos-config/blob/main/testing.json and also the peers mentioned below, but it didn't work on either the dev, qa, or test networks.

```
    tcp://185.69.166.140:9943
    tcp://185.69.166.141:9943
    tcp://185.69.167.141:9943
    tcp://185.69.167.142:9943
    tcp://185.206.122.31:9943
    tcp://185.206.122.32:9943
    tcp://185.206.122.131:9943
    tcp://185.206.122.132:9943
    tls://140.238.168.104:17121
    tls://s2.i2pd.xyz:39575
    tcp://62.210.85.80:39565
```

**Comment by ramezsaeed** [comment]
@A-Harby 
can we check this issue with Ops team.

**Comment by ramezsaeed** [comment]
@A-Harby what is the status here ?

**Comment by coesensbert** [comment]
> @A-Harby what is the status here ?

@A-Harby asked me to have a look and try to find a solution, did not have time yet due to the tfchain issues and recent network outage. Will do some testing today

**Comment by coesensbert** [comment]
Hmz since I started playing around I got 0 connectivity over ygg. Nothing works for me anymore, not even an old version with the peerlist that was working half before starting this.

tf-mon is running 0.4.7 with our peer-list which still has some connectivity, but can't reproduce that anymore on my laptop for example. Rather not start playing around their so to loose all connectivity also for the monitoring.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/88312671/b65fd450-5080-49f1-b62d-0cdf20a27fc6)

Tried some of the newer 0.5.x versions and many different peer list. I was at least expecting for some connectivity using only ygg peers from dev, qa and testnet. But none at all, not on old existing nor new ygg ip's. A combination with public nodes from ygg also brought no result. While peers get connected successfully, no packets can traverse them enough to reach any of the ygg ip's I tested.

I'm afraid a deeper look in debug mode will be required, but the questions then becomes how much time do we spend on this while waiting for Mycelium @xmonader ?

**Comment by zaelgohary** [comment]
Yggdrasil version should be upgraded on all nets now. You may verify and check if you're still facing the issue.

**Comment by A-Harby** [comment]
Verified on Devnet.

The ygg is working again fine; I was able to ping and ssh my VMs using it.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7a839eea-5ec9-4d66-b1c2-49b04f177a8c)

Build version: 0.5.4

**Comment by coesensbert** [comment]
Same here, now mainnet also has newest ygg I have connectivity again using our peerlist
