### ISSUE TITLE
Twin details is empty on the farms page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1606]
### Description

Dashboard, Devnet, https://github.com/threefoldtech/tfgrid-sdk-ts/commit/2d54818c4c44cb4111462b8cd3daea60c60c602a.
A lot of the farms have empty fields in their twin details.

### Steps to reproduce

1. Connect your wallet.
2. Navigate to the farm page from the sidebar.
3. Select a farm.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b01fbe95-d152-4b52-a2d7-90348a1bb0fb)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b14b3f4e-e097-4d9c-b1b9-dc1b5829f60b)

**Comment by mohamedamer453** [comment]
Update:

Investigation:

The issue is originating from the gridproxy since there're no details for these twins. for example:

If we check one of the mentioned farms we can see that its twin id is `100`

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/5339294d-e2a1-48a6-b120-88a946cae29a)

If we searched for id 100 using the twins endpoint it'll return an empty list.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/17a6adc2-191f-4985-9d97-dae361ce57c5)

and that's why it shows `-` in the UI since the returned values are undefined.

**Comment by mohamedamer453** [comment]
I checked multiple farms that were created recently and their data seems to be complete so i think it might have been the mentioned case of a deleted twin and thus i'll move this issue to verification and please while verifying ensure that new/recently created farms have complete data.

**Comment by A-Harby** [comment]
Verified,
Devnet 7b55dd4.

True. Deleting twins was an option on the old dashboard, so that clarified why those farms had no twin details.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8f555e82-f4b2-4ae6-81ce-917783050588)

I also checked newly created farms (with a higher farm ID), and they have twin details.

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 7b55dd4
