### ISSUE TITLE
Two similar requests to load farms on mount

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1681]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/5d14d3ba-1b43-4718-9226-23c3927b4cc7)

**Comment by zaelgohary** [comment]
Already fixed [here](https://github.com/threefoldtech/tfgrid-sdk-ts/commit/9a8047080f3f5bcd78fe7fb259760f3308ff99b7)

**Comment by khaledyoussef24** [comment]
enviroment used to verify : devnet
the issue is not reproducable any more
<img width="1440" alt="Screenshot 2023-12-19 at 9 16 58 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4ff79f0d-7ba4-4cab-86d7-6fec02770be0">
test lodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4156718

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 000eea2

![Screenshot from 2023-12-25 14-14-09](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/0d811fa6-cbb1-4f56-ae92-ecb24fadcb41)
