### ISSUE TITLE
Test Run for All the available solutions

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1763]
Test all the available solution in the dashboard
- [x] Kubernates
- [x] Caprover
- [x] Peertube
- [x] Funkwhale
- [x] Mattermost
- [x] Discourse
- [x] Taiga
- [x] Owncloud
- [x] Presearch
- [x] Subsquid
- [x] Casperlabs
- [x] Algorand
- [x] Node pilot
- [x] Umbrel
- [x] Wordpress

**Comment by ramezsaeed** [comment]
Work In Progress (WIP)

https://app.testlodge.com/a/26076/projects/40893/runs/726768


![Screenshot from 2023-12-21 15-35-40](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/c8cd129c-b66a-4aaf-96d9-dfa25626f461)

**Comment by A-Harby** [comment]
For Caprover https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1678

**Comment by khaledyoussef24** [comment]
For owncloud
1-threefold connect issue
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1750

2-reverting changes issue
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1777

**Comment by khaledyoussef24** [comment]
Discourse 
Couldn't login issue
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1403

**Comment by A-Harby** [comment]
The Caprover node issue is fixed, but documents need updating. https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1768
Peertube, Funkwhale, and Mattermost are working fine, but discourse still faces some issues https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1403

**Comment by ramezsaeed** [comment]
work in progress (WIP)
![SmartSelect_20231224_171416_Chrome](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/91232b1f-9da0-47eb-8d3a-2eb4cd64529e)

**Comment by A-Harby** [comment]
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1763#issuecomment-1868523842
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1763#issuecomment-1866620972

- The Taiga dashboard is working fine with login and adding projects and tasks, but the admin panel is facing an issue with login: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1782.

- Presearch It couldn't be deployed on Dev, QA, or Testnets because the instance needed a node with a large number of resources, and not any of the networks except the mainnet had enough resources for it.

- Kubernetes, Subsquid, CasperLabs, Algorand, Node Pilot, Umbrel, and Wordpress are working fine with passing test cases, and every test case has its screenshots.

**Comment by khaledyoussef24** [comment]
test run completed

kubernetes working fine
mastodon not supported

**Comment by A-Harby** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1788

**Comment by ramezsaeed** [comment]
All work done


![Screenshot from 2023-12-27 11-43-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/683f1ff5-4f49-49ee-85ba-1bdd950bf308)
