### ISSUE TITLE
choose a resilience library

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1800]
We are currently working on enhancing the resilience of our codebase, specifically focusing on asynchronous operations in both browser and Node.js environments. The goal is to identify a resilience library that is simple to use, intuitive, and seamlessly compatible with both browser and Node.js.

We are looking for a resilience library with the following characteristics:

1. **Ease of Use:** The library should offer a straightforward and intuitive API, making it easy for developers to integrate and work with in our  codebase.

2. **Compatibility:** It should be compatible with both browser-side and Node.js, ensuring consistency across our entire stack.

3. **Reliability:** We prioritize reliability in handling errors, retries, and other resilience-related features. The library should contribute to the overall stability and robustness of our applications.

So please: 
1. Research and evaluate resilience libraries suitable for our  codebase.
2. Test the shortlisted libraries for ease of use and compatibility.
3. Provide a report summarizing findings and recommendations.

### Deliverables
Submit a report detailing the research, including insights into the selected library, its usage, and any potential integration considerations.

**Comment by mohamedamer453** [comment]
Update:

Investigation:

Still investigating the available options for resilience libraries, found two main options which are [Mollitia](https://github.com/genesys/mollitia?tab=readme-ov-file#mollitia) and [Cockatiel](https://github.com/connor4312/cockatiel?tab=readme-ov-file#cockatiel) both provide similar functionalities and their functionalities are similar to the needed requirements of our project. still going through the docs of each of them before starting the detailed report and making a decision on which one is better to use in our case.

**Comment by mohamedamer453** [comment]
Update:

Investigation:

Still investigating the available options for resilience libraries, starting to lean towards [Mollitia](https://github.com/genesys/mollitia?tab=readme-ov-file#mollitia) since it provides the same functionalities as [Cockatiel](https://github.com/connor4312/cockatiel?tab=readme-ov-file#cockatiel) but adds a couple of functionalities like `Cache` and `Ratelimit` modules. the only thing left is to continue trying/testing both libraries and make a decision on which is easier to use and more compatible with our project.

**Comment by mohamedamer453** [comment]
After researching resilience libraries that are compatible with both the browser and Node.js environments the following two libraries were found.

### [Mollitia](https://github.com/genesys/mollitia?tab=readme-ov-file#mollitia)

`Mollitia` is a JavaScript Resilience library that works on Node and on browsers. Its purpose is to help organize asynchronous operations under a highly customizable circuit that helps manage error use cases. When everything is falling apart, it stops the classic flow and uses modules to manage failures. It is very similar to the `Resilience4j` Java library, but on Node.


### [Cockatiel](https://github.com/connor4312/cockatiel?tab=readme-ov-file#cockatiel)

`Cockatiel` is resilience and transient-fault-handling library that allows developers to express policies such as Retry, Circuit Breaker, Timeout, Bulkhead Isolation, and Fallback. similar to .NET's `Polly`

***

both libraries are similar to each other and support the same functionalities but according to the docs `Mollitia` supports two more modules which are the [`Cache`](https://genesys.github.io/mollitia/api/module/cache) and [`Ratelimit`](https://genesys.github.io/mollitia/api/module/ratelimit) modules and it also supports a Prometheus add on that adds metrics on every circuit and module.

So that's mainly the reason for leaning towards `Mollitia`. 

***

### Mollitia Usage

Using `Mollitia` appears to be pretty simple, it starts with creating a `Circuit`

```ts
import { Circuit } from 'mollitia';

// Creates a circuit
const myCircuit = new Circuit({
  name: 'new circuit'
});

//Using the circuit
const myString = await myCircuit.fn(functionName).execute(functionParameters);

```

and after that you can add different logic to the circuit by using the available modules. all modules can be found [here](https://genesys.github.io/mollitia/overview/introduction) under `Core Modules`

```ts
// Imports needed components
import { Circuit, Retry, Timeout } from 'mollitia';

// Creates a Retry Module
const retry = new Retry({
  attempts: 2, // Will retry two times
});
const timeout = new Timeout({
  delay: 500, // Will timeout after 500ms
});

// Creates Circuits
// This will retry first then timeout
const retryWithTimeout = new Circuit({
  options: {
    modules: [retry, timeout]
  }
});
// Note that rearranging the modules will result in a different logic
// This will timeout first and won't retry
const timeoutRetries = new Circuit({
  options: {
    modules: [timeout, retry]
  }
});

```

***

### Other features

Another feature that `Mollitia` supports but i didn't try yet is the Prometheus add on that adds metrics on every circuit and module so that you can monitor and analyze your applications.

Full docs for the Prometheus section can be found [here](https://genesys.github.io/mollitia-prometheus/).

***

### Potential integration considerations

I created a circuit and tested it with the [single vm deployment script](https://gist.github.com/mohamedamer453/28ac7d2b43ee01f52b546a46eb018d4c) and it seemed to work fine, not quite sure about other implementations but since it has native typescript support i suppose that it wouldn't pose any potential limitations.
