### ISSUE TITLE
Stats: Invalid countries count.

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2002]
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/4e11b0eea16c2f9e31c3ed0b1dd84ea14bb70ef4/packages/new_stats/src/utils/stats.ts#L10

we should'n add the value, we should get the  countries from the length of the nodesDistribution at `mergeAllStatsData`
``` ts
 res.countries = Object.keys(res.nodesDistribution).length;
```

**Comment by A-Harby** [comment]
Verified,
Devnet, stats site.

From devnet we get Belgium and Canada.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/28b80ac7-7bc8-4f3b-9812-57c29de83f63)
And from testnet we get Belgium, France, Netherlands, and United States.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0faa6c62-a69a-4f12-9ac8-021f48eb879a)

And both are being counted as 5 correctly (not 6 because Belgium is duplicated).
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3ed0058b-5af7-4d66-bc8d-2a56c30d3d6d)
