### ISSUE TITLE
Minting is reporting large number of uptime days

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2004]
### Description

Devnet and Ninja 2.3.0-alpha6.

The mining report for some months is reporting more days than in a month (even in billions of days)

All the receipts are at: https://alpha.minting.tfchain.grid.tf/api/v1/node/26.

Hash example: `c3f9c2449761983224a57dcd94ed1af433782b5706014bf73588213a1a5ffa0f`
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8d879155-71e5-4811-8b94-0363b3608e13)

A clear description of the bug, including relevant identifiers like:

- **Node ID**:  26

- **Farm ID**: 10

### Steps to reproduce

1. Navigate to the dashboard
2. Navigate to the TF Minting Reports.
3. Insert the hash receipt.

**Comment by ramezsaeed** [comment]
![Screenshot from 2024-01-17 13-11-54](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/7bddaabe-24f7-48d8-8b61-6555a9b4908e)

**Comment by LeeSmet** [comment]
Yes, there was a bug for 2 or 3 months some time ago which caused the uptime in the report to be largely inflated. Since this is only a problem for the report (actual tokens are not inflated accordingly, and the token payout matches what is in the receipt, and the payout also includes the hash of the receipt with the wrong uptime) these haven't been regenerated.
