### ISSUE TITLE
Alpha Minting: Cannot Paste only write

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2042]
# Issue

A farmer tried (on 2 browsers) to get the minting info using Alpha minting tool on the dashboard, and could only write in the box, not paste.

[See this forum reply](https://forum.threefold.io/t/minting-receipts-on-the-threefold-dashboard/4197/2).

Update: The setup was windows 10, chrome and firefox.

**Comment by mohamedamer453** [comment]
Update:

The issue seems to be only present in the old dashboard, in the new dashboard copy/paste are working fine as seen below.

[Screencast from 28-01-24 13:58:43.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ffe4e382-90cf-4966-8386-717d8485192d)

Will move this one to verification since it seems to be working fine in the new dashboard.

**Comment by A-Harby** [comment]
Verified,
Devnet, 7b55dd4.
The copy and paste are both working fine, just as they are in writing.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/81f51954-c0ea-49e0-82a5-6aec944ce5db)

**Comment by ramezsaeed** [comment]
@A-Harby 
can we please verify this on windows

**Comment by A-Harby** [comment]
Verified, Devnet e567b7d.
On windows and paste is working fine with no issue.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/69663b22-20e7-4b0e-b9c6-3c82a592a687)
