### ISSUE TITLE
make dedicated nodes rentable from `node finder` and from selecting node while deploying any solution 

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2056]

**Comment by Mahmoud-Emad** [comment]
Should be done in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2422

**Comment by khaledyoussef24** [comment]
verified on devnet
version : e7030e6
the main feature of renting node from the node finder while deploying is that it works fine.
found a node from the node finder then searched for it while deploying a vm

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/edd69b63-6042-4340-9055-1787d7e7e8e1)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c3e03965-4040-475c-bfe2-805fee219fe3)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/29920925-e567-4088-b28a-03a401420018)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5e975236-41b0-4942-8d07-905c4eca3b82)

can the dedicated filter while searching for nodes show dedicated nodes which are not rented
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/99ade865-dd67-4e64-b327-c7016338deaa)

and also after renting the node the reserve button when finishes loading it does not change to reserved and the red color
you have to go back to filters and enable dedicated filter then you can choose the node to deploy.
and also un clear error appears when you try to rent the node again after you already rented the node.
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/29920925-e567-4088-b28a-03a401420018)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a3880432-8c4b-4d25-b3fd-163527e5adb6)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6f2638d3-6c89-4fdd-86e8-7364455df5dd)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b9e0be8e-017c-4783-8ed2-104f2785a82a)

**Comment by zaelgohary** [comment]
WIP: 

Issue happened because the node wasn't being updated after reserve/unreserve. Tried multiple solutions like editing the changes manually then emitting them to selection component or calling the node again from proxy or grid client after few seconds but all didn't work and I'm not sure why. Will try another solution tomorrow.

**Comment by zaelgohary** [comment]
Work completed:

Implemented v-model instead of dispatching multiple events across different components. As a result, the v-model automatically updates whenever the "rentedByTwinId" key of the node card is modified. These modifications are also reflected in the Node Finder page and during auto-selection. For manual selection, an event is emitted instead of the previous method, considering that the data originates from either the model value or a placeholder node, making this solution the most suitable.

**Comment by khaledyoussef24** [comment]
all reported issues are now fixed and working fine
verified on devnet
version : d2e641f
scenarios tested:
rented the node from the node finder in the deployment section
tried the filter dedicated after renting and worked fine
the reserve word changed succesfully

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5867f2cb-0977-475e-92c8-7d08b3490cec)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6e9532bd-2b2b-4f39-ade9-8b1028b36736)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2cc473a1-959c-4a3d-9669-4bef6a25555e)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/463cc933-61ea-4f40-a012-8e7209073383)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4270467
