### ISSUE TITLE
Add links checker workflow

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2219]
The target is to know if there are broken routes or changed docs URLs.

**Comment by zaelgohary** [comment]
WIP:

Working on adding a workflow that check links in repo then opens an issue if broken links are find.

**Comment by zaelgohary** [comment]
Work completed:

Added a workflow that checks for all links in https://staging.dashboard.dev.grid.tf/#/ and it would run daily at 8 am.

**Comment by A-Harby** [comment]
The workflow has been added here, https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/.github/workflows/link_checker.yml and it is working fine and passing since it was merged here. https://github.com/threefoldtech/tfgrid-sdk-ts/actions/workflows/link_checker.yml.

@zaelgohary But maybe you should also make the test for all four other networks? It would be good to make sure that all of them are working fine if any changes happen anywhere (like changing a manual link that will affect the mainnet but not the staging).

**Comment by zaelgohary** [comment]
> @zaelgohary But maybe you should also make the test for all four other networks? It would be good to make sure that all of them are working fine if any changes happen anywhere (like changing a manual link that will affect the mainnet but not the staging).

Manual links are the same in all networks.

**Comment by A-Harby** [comment]
> > @zaelgohary But maybe you should also make the test for all four other networks? It would be good to make sure that all of them are working fine if any changes happen anywhere (like changing a manual link that will affect the mainnet but not the staging).
> 
> Manual links are the same in all networks.

Make sense and the workflow is working fine https://github.com/threefoldtech/tfgrid-sdk-ts/actions/workflows/link_checker.yml.
