### ISSUE TITLE
Playground is assigning invalid public keys to new accounts

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#238]
On mainnet, I just created a new account with the "Create Account" button:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/17682591/56f5e248-c0da-41ec-b7a7-f4c5c7cc97f2)

Then I check the public key for this account (and several of those created before it:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/17682591/1eccd0d2-00f2-4075-bb55-06bb66e6df05)

These are not valid public keys, and the user will see all nodes as down according to the capacity filter since they can't use RMB.

I think maybe this issue has already been addressed in the most recent code, but it's occurring now on mainnet and users are seeking support. Can we get a patch pushed out asap?

**Comment by scottyeager** [comment]
Also documenting a workaround here. By setting the public key and relay to null, we can get the playground to generate a valid key.

First update the twin via the Polkadot UI. Enter the twin ID and leave both inputs unticked:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/17682591/425c3599-62c3-4ca9-9561-8cd380d8524c)

Then submit the transaction. After that, return to the playground, close the tab and open a new tab with the same profile (refresh might work too, but didn't in my incognito windows for testing).

**Comment by A-Harby** [comment]
I tried creating an account on the mainnet from weblets and it had a wrong public key. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/db525a69-2a82-4c85-baad-fc6ca2c0f8c4)

And I also tried the same steps on devnet and it was fixed.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a2ddfb84-9e5a-47ed-9969-e39cc8166bd8)

But as @scottyeager said it will cause a problem on the mainnet as user wont be able to deploy any solution because all the nodes would be down for that twin.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The Public Key is generated correctly upon account creation from the weblets.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/2d8a2b8a-83c9-49ab-a76a-96fde3428b75)

and after funding the account and adding a public ssh key, the nodes in the capacity filter were successfully returned as online and the twin was able to communicate with rmb.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/372b44fb-2818-4105-ab27-c86ba2defa94)

And since there were no mentions of a hotfix for mainnet and the issue was returned to verification after @A-Harby 's comment then i think it'll be included in the next release and this issue can be closed.

**Comment by scottyeager** [comment]
When does the next release go live?

**Comment by mohamedamer453** [comment]
> When does the next release go live?

I'm not sure about test and mainnet but it's supposed to be live on qanet soon.
