### ISSUE TITLE
🐞 [Bug]: revalidate the IPs range inputs

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Revalidate all the inputs in adding a range of IPs to the farm when any of the from or to IPs change.
and gateway should also be checked.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c19b9ccd-a1a1-4f83-b75b-32440e4bff73)

### which network/s did you face the problem on?

Dev

### version

333317a

### Relevant screenshots/screen records

[screen-capture (20).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6696229a-86f9-444b-a0da-94ad43ae38c4)

### Relevant log output

```console
.
```

**Comment by Mahmoud-Emad** [comment]
## Issue update 

### Investigation and Solution, Work done:

- Found an issue when validating the gateway and fixed it, that issue happened if the first or last IP wasn't valid, so we called the `getRange` function to get the range of those IPs, then validate if the gateway IP included in the range

- Revalidating the form to give another look on the form before updating it

**Comment by A-Harby** [comment]
Devnet, 44f15ae.

Also the gateway to be in the same range as IP range validation is removed. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5ae52711-49b6-4b99-847c-3efdc14916ba)

**Comment by Mahmoud-Emad** [comment]
@A-Harby 
fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2933

**Comment by A-Harby** [comment]
What do you mean by the same version? Did you mean the same `range`?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e96e2d2a-0136-4ca2-ba2f-47625d07fdf2)

And there's a case not covered that gets the dialogue to crash.

[screen-capture (13).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5f3e7b37-8931-4e15-a5b1-bb907cb66073)

**Comment by Mahmoud-Emad** [comment]
@A-Harby 

The `Cannot get range of two IPs if they are not both valid and the same version` message is generated by the `getIPRange` function from the `get-ip-range` package. The term `version` here refers to the IP version (e.g., IPv4 or IPv6). For more details on IP versions, please refer to [this Wikipedia article](https://en.wikipedia.org/wiki/List_of_IP_version_numbers).

What is an IP version?

In your example, you used `1d`, which can exist in an IPv6 address. When we attempt to compare the `First IP` and the `Second IP` within a range, the helper function encountered `1d` and mistakenly treated it as if an IPv6 address (`V6 version`) was being compared to an IPv4 address (`V4 version`). This mismatch is not valid and hence causes the error.

However, a `Try|Catch` block is needed to avoid this error, the issue should be fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2936

**Comment by A-Harby** [comment]
Verified, Devnet 6f2ebd3.

The re-validation is now working correctly and all the validation cases are covered again.
and the validation error isn't happening anymore.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/722660f3-4aad-4cc4-9f95-49576b6472d8)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/348203de-d647-446c-ac93-07d8cad2eb8f)

[TC2208 - Add Multiple IPs to a Farm](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150417)
