### ISSUE TITLE
When click 'deploy' move to the error input

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#2741]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe
Sometime user not able to find where the problem is in his deploy form

### Describe the solution you'd like

We had the same solution in mastodon project

**Comment by A-Harby** [comment]
Blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2831

**Comment by A-Harby** [comment]
Can we mark the missing inputs red, give them alert and explain what is wrong when going back to it?

[screen-capture (10).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3604dcf0-0bf0-425c-945e-c9f476485412)

same here, and also shouldn't the user move to error here? Move the user to the load nodes as the error is from the node, and if the user tries another node, it will work (not changing the region or any of the node filters).

[screen-capture (9).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ae08bed7-203d-472d-acce-893fec5b56bf)

**Comment by A-Harby** [comment]
Verified, Devnet 1b19f4f.

The deploy button is a much better option to help the user identify what is missing or wrong, instead of the old option to just disable the button.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0ce08e29-70b4-477c-98ae-40b0664e8ebb)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7f7d1260-bdaf-4868-9d58-8828907c75ac)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/98783097-89ea-4506-a06b-cabafdb21a4c)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/865b0161-f9f8-4b6b-be85-ce7ba1a13d97)

[TC2720: Deploy button points to missing/wrong input](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4295384)
