### ISSUE TITLE
🐞 [Bug]: Info message Enhancement for gpu deployments

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

even when I have a rented node and the node is choosen filter is on I see this message while deploying 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/80b1080e-e1c2-403f-b7b5-fd8cfce5cfe7)
may we add also another info message above the gpu card field to  the user to choose gpu cardf 
 `Choose GPU card to deploy your vm`

### which network/s did you face the problem on?

Main

### version

2.4.2

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by amiraabouhadid** [comment]
Work done: 
added alert with `Choose GPU card to deploy your vm` above gpu cards field
Could not debug why filters are misbehaving due to the following errors on mainnet 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/849e8dab-7e16-4130-ae40-fcf55a52242e)
On testnet, no nodes were found with GPU

**Comment by khaledyoussef24** [comment]
verified on devnet
version : db2daf4



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3eef88c4-2e75-4154-a190-30b0abe02a16)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/74719087-d8b7-4400-9ce4-99d7cdba3b9f)
