### ISSUE TITLE
🐞 [Bug]: Some nodes fails to load perf tests results

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

the same issue for #2733 occurs on some nodes on mainnet.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/17a36e6d-5c5a-4f45-abae-b49200c16d84)
but this time the network speed test and also the cpu benchmark test.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/eed0b7c9-fc3c-4a80-bc07-250a5a23e343)

### which network/s did you face the problem on?

Main

### version

1479

### Relevant screenshots/screen records

,

### Relevant log output

```console
.
```

**Comment by zaelgohary** [comment]
Investigation:

I tried checking the IPerf details & CPU benchmark but the error was not displayed.


Node 2733: (Nodeis down that's why the 2 cards ID not show)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/442f5499-d358-40e6-af12-ce9decd41342)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/56cf57ae-3d63-493c-8b09-58a1812adab7)

Node 1479: (I'm not yet sure why the 2 cards are not being displayed)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/ed356b67-b575-444d-ac85-23c53c26fb4a)

**Comment by zaelgohary** [comment]
Investigation:

I got the same error in the issue while trying to get the Iperf & CPU benchmark in node 1479. I also, got the following errors in the console. 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/80b47fea-2c55-42b8-9286-19f23ed87079)

Issue happens because zos version is not being updated.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/dfa13210-109a-455a-b9a6-93f2c9d21f56)

Issue should be solved once  [issue](https://github.com/threefoldtech/zos/issues/2347) is done.

**Comment by zaelgohary** [comment]
As stated [here](https://github.com/threefoldtech/zos/issues/2347#issuecomment-2139402267), the issue happened because node needs to be updated and this can happen only from the farmer's side.
