### ISSUE TITLE
🐞 [Bug]: (MainNet Verification) GPU node with no gpu cards

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

rented a GPU node but while deploying a gpu vm i did not found a gpu card in the node
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0b16fd82-4fe3-4db2-bcbc-e7903edf10d2)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/38e1827a-8779-438d-8903-97460ca82c93)

### which network/s did you face the problem on?

Main

### version

5011

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by khaledyoussef24** [comment]
maybe it also related to #2770

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work in Progress (WIP):

The issue might have occurred due to a bug in the `Grid Proxy` rather than the `Dashboard`. I rented more than one node, and all worked fine as I could view the GPU details of the nodes. However, I encountered a problem with one node as I could not list its GPU. After investigating, I discovered that the node's GPU returned a `null` value from the grid proxy.

This is a [valid node](https://gridproxy.grid.tf/nodes/14/) and this is its [GPU](https://gridproxy.grid.tf/nodes/14/gpu).
This is a [not valid node](https://gridproxy.grid.tf/nodes/5856) and this is its [GPU](https://gridproxy.grid.tf/nodes/5856/gpu).

**Comment by khaledyoussef24** [comment]
verified on mainnet
version : 2.5.2

the grid proxy now may response as 

![Image](https://github.com/user-attachments/assets/165ecae8-7701-4939-9880-e33f9872ced6)


![Image](https://github.com/user-attachments/assets/0c6cc34e-c85d-4f4c-90ba-81a9835192e7)



![Image](https://github.com/user-attachments/assets/684d07c9-2f33-4fcc-ad28-f6bf9838a4a1)



searched for some nodes could not find the same issue

**Comment by khaledyoussef24** [comment]
is there anything more i can do to verify ? @Mahmoud-Emad
