### ISSUE TITLE
contracts table takes too much time to load

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2802]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

after changing the view of contracts if user used 5 contracts per page every time the user change the page it takes too much time
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/77edb1d4-8ab1-4737-979a-3cf8770dd091)

[Screencast from 05-28-2024 05:42:31 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5c39ff1f-baa4-48ee-9def-86550c88986d)

### Describe the solution you'd like

is there a way so all the contracts load in one request so changing the page wont take this long.

**Comment by Mahmoud-Emad** [comment]
## Issue update 
### Work done

Enhance the contracts list by removing the duplicate requests, and reduce the time limit when loading the contracts by removing the `onMounted` lifecycle

#### Changes

- Removed the 'onMount' from the 'onMounted' life cycle since it is not needed because we call the 'loadContracts' function on each change that happens on the table.
- Fix the contracts table takes too much time to load.

#### Screenshots/Video

 [Screencast from 06-04-2024 06:46:01 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/1ae65b10-66d1-4666-860a-b3d662092af4)

**Comment by khaledyoussef24** [comment]
verified and working fine now on devnet
version : ad30945
loading contracts time is now acceptable 


https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/75ed81e8-4ee2-4e6a-a286-c346c3c266f7
