### ISSUE TITLE
🐞 [Bug]: Farm ID is empty on rent contract table

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

On your contract page, the farm ID field is empty on my rented node.

I also faced another issue where the node status did not show anything. I can't reproduce now.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a73d82de-9668-4865-acbd-9a943cdeae34)

### which network/s did you face the problem on?

Dev

### version

b72ee05

### Twin ID/s

1174

### Node ID/s

73

### Farm ID/s

57

### Contract ID/s

119696

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8ca44b8c-0fff-4fa3-8bd4-da61157bea9f)

### Relevant log output

```console
.
```

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Investigation and Solution:
The issue is not valid now, since we updated the contracts page in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2872 I used the same account of you and I was able to see the farm id and the status with the correct color.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/ade9ea33-79f4-4c4e-a799-1d7f59e50c54)

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Investigation and Solution:

There was a mismatch field between the `Node Type` and the `Rent Type ` IDs in the table fields

### Work done

Updated the keyword `farm_id`

**Comment by A-Harby** [comment]
Verified on Devnet, 9ce9f80.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bca5e186-195f-4719-b98d-da256eb61b8c)

[TC2315 - List Rent Contracts](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4156522)
