### ISSUE TITLE
Update the script of deploying a vm with Mycelium 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3296]
Add how to:

- [x] Generate a seed for the network and the vm.
- [x] Let the client generate it for the user.
- [x] Use old Mycelium seed to obtain the same old ip.
- [x] Document the full example in the [grid_info](https://github.com/threefoldtech/info_grid) repo and mention the PR

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done

Updated the `single_vm_mycelium` script with some details about the MyCelium options

#### Changes

- Documented the `mycelium` option
- Documented the `myceliumSeed` option
- Documented the `seed` option
- Generate the seeds during the deployment instead of hard-codded them

#### Documentation PR

- https://github.com/threefoldtech/info_grid/pull/626

**Comment by khaledyoussef24** [comment]
verified 
the script is updated and working file and with more extra info


![Image](https://github.com/user-attachments/assets/21e4f373-d4ac-46c9-9578-b7833b8bcc1e)



![Image](https://github.com/user-attachments/assets/e5da35c4-715d-454e-99ef-6f0334807e61)
