### ISSUE TITLE
🐞 [Bug]: Connect your wallet is removed!

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Login as a new user (from incognito or new browser), can you can't see Connect your page anymore.

### which network/s did you face the problem on?

Dev

### version

28e17de

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/1d6cb66d-770b-4da5-8fd9-325d946b1ac0)

### Relevant log output

```console
.
```

**Comment by Mahmoud-Emad** [comment]
That happened because we normally save your hashed password into the local storage, since you opened a new browser you don't have rather wallet nor saved passwords, connected (saved passwords) you'll see the tab of `connecting your wallet` instead of `login your wallet` 

This is an example from an incognito browser

![Image](https://github.com/user-attachments/assets/831e86d7-6040-4c36-b95a-5372b471d766)

another browser

![image](https://github.com/user-attachments/assets/23633be9-503e-48a9-8e65-2bb7667043cc)

**Comment by 0oM4R** [comment]
I will give it about **1hour** for investigation

**Comment by 0oM4R** [comment]
Issue update : the cause is we are checking the active tab index 0,1 but actually we are `in case of no credential stored` we are passing array of one elment as tab, which is the connce wallet so the body of  login appears.
will work on the solution tmw

**Comment by 0oM4R** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/commit/28e17def150db77b2afd6f0faad40f41d28b1e2f
just figured out that is this pr broke the logic, idk why yet but it is working fine on the commit before it.
will give it more **2 hours** of investigation to avoid changing the current profile manger logic

**Comment by 0oM4R** [comment]
the issue is we are using async component to avoid load clients before set the stack url, but this lead tof unexpected behavior in the profile manager url. will investigate how should we resolve this issue, will update the estimated time to **8 hours**

https://github.com/threefoldtech/tfgrid-sdk-ts/commit/28e17def150db77b2afd6f0faad40f41d28b1e2f#diff-39ab5393f74aa973412e9e454bf2f8d5725c108b2b42d6f7d62e30d04acf72a1R26-R28

**Comment by 0oM4R** [comment]
Issue update :
**work completed**; The issue was that we were importing the d-tabs component using defineAsyncComponent to avoid initializing [clients](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/clients/index.ts) before setting its urls by ServiceURLManager, This made the ProfileManager mount before the inner component Dtabs got imported.

**Comment by 0oM4R** [comment]
will add 24h as estimated time for review

**Comment by A-Harby** [comment]
Verified, Dev a66e759.

Its back to normal.
![image](https://github.com/user-attachments/assets/bebe63c9-c4b5-4c3a-9f5d-39458e53c3fb)

[TC2118 - Create a new twin](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=442285#case_4150327)

**Comment by A-Harby** [comment]
Devnet, a948bfa.

It got back to the same error again!

![image](https://github.com/user-attachments/assets/baa57e2e-e789-432e-bbf7-785522300343)

**Comment by 0oM4R** [comment]
this issue returned on https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3347, Rabie will investigate on this with the lazy load issue.

**Comment by khaledyoussef24** [comment]
while using private browsing in chrome and using also safari and firefox
can not find the Create Account tab while opening the dashboard.
![Screenshot 2024-09-29 at 1 53 47 PM](https://github.com/user-attachments/assets/8a018672-5b41-405f-bcc4-1edd8d102cdc)

**Comment by ramezsaeed** [comment]
Also cannot find it on firefox
![Screenshot from 2024-09-29 14-01-15](https://github.com/user-attachments/assets/1a16b886-d96d-431f-9670-0a67f23ac9c2)

**Comment by 0oM4R** [comment]
> this issue returned on #3347, Rabie will investigate on this with the lazy load issue.

should be solved in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3475
@ramezsaeed @khaledyoussef24

**Comment by khaledyoussef24** [comment]
verified issue is no more longer reproducible
tested in safari and private mode

version : 038404b
![Image](https://github.com/user-attachments/assets/00b9a1c7-2ece-4280-9a07-7d67c998a607)
![Image](https://github.com/user-attachments/assets/e02152dd-8924-42cb-b6fd-ed5c35757742)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- a516b1b
- chrome

![Screenshot from 2024-10-23 22-02-21](https://github.com/user-attachments/assets/b9eee5c6-a83a-488a-88cd-922bb33a97dd)
