### ISSUE TITLE
🐞 [Bug]: `Lazy Loading` Can not load Contracts 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

loading contracts showing unclear error

### which network/s did you face the problem on?

Dev

### version

a542a73

### Relevant screenshots/screen records

<img width="1680" alt="Screenshot 2024-08-20 at 5 41 00 PM" src="https://github.com/user-attachments/assets/b85f0c67-69f2-4fa9-ae4f-5c2f0e8b4b02">

### Relevant log output

```console
.
```

**Comment by amiraabouhadid** [comment]
check url error in screenshot (4th)

**Comment by 0oM4R** [comment]
Issue update:
I found that this happens because the `TfContractsList` is calling the clients/index.ts before setting the stacks urls, this happens randomly will continue investigating

**Comment by 0oM4R** [comment]
What happens: 
many components and utils files are using the clients/index.ts
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/c573f1a06b0b71fbc8162ace62c455e3a00ca082/packages/playground/src/clients/index.ts#L1-L9
this exports the three clients, that was fine until we introduced the `Url Monitoring` feature this features set the urls in the `window.env` after pinging them on mount the app.
in some case the file `index.ts` got loaded before initializing urls values so the created clients got undefined url.
the issue is not from lazy loading, the issue is we are using the clients in many places and we aren't sure about its value!
the lazy load feature is great and helps for improving the performance, and i suggest to use it in all large components but we need to handle the clients we are using without checking if they are working or not!

Suggestion:
store the clients on store as grid, This will cost many changes but i think it worth that

**Comment by ramezsaeed** [comment]
Got the same erorrs

![Screenshot from 2024-09-29 11-53-55](https://github.com/user-attachments/assets/e2ee0cda-3fc5-4a6d-8974-9dadfb925bea)
![Screenshot from 2024-09-29 11-55-25](https://github.com/user-attachments/assets/b2280d57-3fdd-495a-bbdb-a15ae6382849)
![Screenshot from 2024-09-29 11-51-21](https://github.com/user-attachments/assets/3da4c530-1a7e-4282-8af4-c66554224665)


[Screencast from 09-29-2024 11:49:35 AM.webm](https://github.com/user-attachments/assets/cab2be00-4c15-4fd0-945a-299cd14db053)

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : 205fd89
the issue is no longer reproducible 
tried to produce it in diifferent accounts but still working fine
![Image](https://github.com/user-attachments/assets/9d84649e-3bba-4138-813d-6f13fdfc4744)
