### ISSUE TITLE
🐞 [Bug]: The compare_locked_balance.ts script doesn't work properly with Devnet

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/tfgrid-sdk-ts#3498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

- When attempting to run the compare_locked_balance.ts script with the Devnet configuration, no data is displayed. However, it functions correctly with the Mainnet configuration.

![compare_locked_balance](https://github.com/user-attachments/assets/34ebc924-c3c1-4993-9542-142d66ea9e33)

### which network/s did you face the problem on?

Dev

### version

205fd89

### Relevant screenshots/screen records

n/a

### Relevant log output

```console
n/a
```

**Comment by zaelgohary** [comment]
@atefnazmy The purpose of the script was to compare the frozen balance with the amount locked in those contracts as mentioned [here](https://gist.github.com/zaelgohary/e870da12a442eb9f4a981ca5e66b53e7)

This was done to identify the mismatch in balance to fix it. The fix is already done and released on devnet but hasn't reached main net yet. Once it reaches main, the function should return an empty array, too.

**Comment by atefnazmy** [comment]
Thanks for the clarification.
