### ISSUE TITLE
Use gateways with wireguard backends in playground solutions

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#502]
check how to use it [here](https://www2.manual.grid.tf/javascript/grid3_wireguard_gateway.html)

**Comment by mohamedamer453** [comment]
Verified on devnet.

After deploying a Peertube instance from the playground i checked the details of the contract and it can be seen that the `backends` uses the private ip from the wireguard config instead of using the planetary ip.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/277baec3-4edb-473c-b9aa-20952fd274df)

and the instance itself is working without any issues.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/fabf655d-eb01-477c-a15e-cba606a6a65b)
