### ISSUE TITLE
The balance view needs more info

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#537]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/e8d49d59-211d-4a78-86ed-170e1bf4e924)

1- locked needs to have a link to locked balance docs
2- when you open the profile manager there needs to be references for the information of the locked balance as well

**Comment by mohamedamer453** [comment]
> 1- locked needs to have a link to locked balance docs 

was added and now it redirects to https://manual.grid.tf/tfchain/tfchain.html?highlight=locked#contract-locking

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/02382e75-a3ee-491a-9b46-8a9c3d318305)

however the balance need some padding because now its almost clipped by the taskbar above it.

>2- when you open the profile manager there needs to be references for the information of the locked balance as well

Nothing was added in the profile manager.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/6059b95d-9ebf-48f6-9443-ba7667a42ddc)

**Comment by xmonader** [comment]
After the changes with the locked tokens link, i believe it's safe to close the issue
