### ISSUE TITLE
Issue in deposit & withdraw modals

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#582]
### Description

try to open the deposit modal then click outside then click the withdraw modal then go back to the deposit modal and notice if it works expected

[Screencast from 13-06-23 18:02:55.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/c8023688-5878-47a1-9004-b459d9efd1d0)

**Comment by 0oM4R** [comment]
__Status__: merged waiting for release

**Comment by A-Harby** [comment]
QA 2.0.0-rc14.

the update made the deposit hard to use, since the main use of the tab is to give the user his twin destination and memo text.
The moment I click on any of the tab is automatically closes, making copying any data kinda impossible to do.
[TF DASHBOARD (1).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6e47c1a8-e69b-40f2-9b52-0c928b42d2dd)

**Comment by 0oM4R** [comment]
waiting for release

**Comment by A-Harby** [comment]
Verified on QAnet, 2.0.0-rc15.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/46d1e90f-c044-494f-ac11-ca5ed7241291)
