### ISSUE TITLE
As a user I should be able to use my domains for my solutions

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#670]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/ae5a0de7-941f-414d-9254-58f52f1cf4a5)

Right now, almost all of the solutions except for caprover depend on creating records on the gateway, where you end up with something like `wpInstance318.gent01.dev.grid.tf` which isn't that friendly, and probably I'd like to use my own domain e.g `myblog.com` instead

I think we probably need to allow the user to set a custom domain directly here as an option next to subdomains on our gateways, and if the solution using public ip we should ask the user to set an A record in their name provider, otherwise we create an FQDN reservation and ask them to set the A record to the gateway IP

**Comment by MohamedElmdary** [comment]
Some tips for solution:
- add switch (enabled if the user is using public ip otherwise it's disabled and the gateway dropdown is shown)
- if the user enabled the switch to add a custom domain (we should show a v-text-field to allow him to write his custom domain and make sure to validate that domain)
- If the user has no public ip so we can't use custom domain (so we show him a warning at the end of deploying process telling him the public ip of the gateway to let him register that ip on any domain provider e.g name.com)

What to do:
- accept props (`hasPublicIP`: indicates if the user selected ipv4 or ipv6)
- add toggle switch with tooltip (text should change based on the different variables) (should be disabled if `hasPublicIP: false`)
- add `v-text-field` with **your custom domain** to allow the user to write his custom domain if he enabled the switch
- make sure to disabled the switch and return back the `v-select` of gateways based of `hasPublicIP` value

`Note: move *gateway select* and *custom domain input* into their own components so they get destroy and remount everytime he toggles the switch`

**Comment by 0oM4R** [comment]
__Update__: worked on the ui and this is the current result.
[Screencast from 12 يول, 2023 EEST 06:24:36 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/4deb61fa-7090-4b16-a8c3-05557fd2e43a)
some points to work on tmw:
- warp the switch and the two gw components in a generic component
- change tooltips
- modify fqdn field and make it shows node ids
- deploy script needs to be modified too

**Comment by 0oM4R** [comment]
implemented the logic to find the nearest gw node for fqdn workload

[Screencast from 13 يول, 2023 EEST 09:51:54 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/43ca7916-64b7-4116-8d7e-a9f39837d02d)

**Comment by 0oM4R** [comment]
I can say the deploying flow is ready and tested;
faced some issue with rollback, fqdn constrains, and delete deployment.
need to add the after deploy message and apply the new flow for the rest of solutions

**Comment by 0oM4R** [comment]
__Update__: all done, tmw will use the new component in the required solutions

**Comment by 0oM4R** [comment]
__Status__: pr #820 ready for review 

please make sure to test it well in all related weblets

**Comment by khaledyoussef24** [comment]
verified peertube

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/48c63262-f0c3-4326-a2b6-7b3f1b6c1c13)
![Screenshot from 2023-07-20 14-27-28](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/72a720e4-2cee-4c13-91cb-a6b7f6114347)
![Screenshot from 2023-07-20 14-27-20](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/92161cb6-88b1-4ab0-af64-ef06b791f5c9)
![Screenshot from 2023-07-20 14-02-47](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/76fa631c-e7a3-45c8-bc34-aed385a1a693)

funkwhale verified
![Screenshot from 2023-07-20 14-52-50](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/93b1b42f-b1d5-4133-9038-deb4c4fb1d3a)
![Screenshot from 2023-07-20 14-49-22](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c0e90b71-a2bc-4bfb-bd89-70c08b950df0)

**Comment by khaledyoussef24** [comment]
discourse while using domain name gives 404 not found
![image_2023-07-20_15-19-16](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/04870855-6431-4132-a0b0-930f4f2b1aaf)

while tried to deploy without domain name worked fine and image is up
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/66f75b8b-68e4-4e7d-937f-dacf95703009)

**Comment by 0oM4R** [comment]
> discourse while using domain name gives 404 not found ![image_2023-07-20_15-19-16](https://user-images.githubusercontent.com/110984055/255527492-04870855-6431-4132-a0b0-930f4f2b1aaf.png)
> 
> while tried to deploy without domain name worked fine and image is up ![image](https://user-images.githubusercontent.com/110984055/255527378-66f75b8b-68e4-4e7d-937f-dacf95703009.png)

should be fixed in #842

**Comment by khaledyoussef24** [comment]
discourse now is working fine with domain names 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7a941ddc-d729-4728-8530-1f90813488ce)
