### ISSUE TITLE
Add search capabilities in dedicated nodes page

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#721]
should support search with:

- CPU
- memory
- SSD disk
- HDD disk
- GPU's vendor
- GPU's device

require: https://github.com/threefoldtech/tfgrid-sdk-go/issues/209

**Comment by Mahmoud-Emad** [comment]
Currently working on handling the old implementation and re-implementing the feature from scratch to match the nodes table inside the explorer.

**Comment by Mahmoud-Emad** [comment]
WIP: The search keys you requested are now supported on the 'portal/dedicated nodes' page, alongside the table

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/42326c3a-2aec-42a7-adb2-f5fb319f747a)


I am currently awaiting updates regarding the [necessary issue](https://github.com/threefoldtech/tfgrid-sdk-go/issues/209) in order to support the newly added keys and provide an accurate outcome.

**Comment by Mahmoud-Emad** [comment]
Working on it, the proxy indexer were added

**Comment by Mahmoud-Emad** [comment]
The [mentioned pull request](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/730) is ready for review, will move this issue into verification column once it got merged

**Comment by mohamedamer453** [comment]
### CPU filter

The cpu filter is not working with any value.

[TF DASHBOARD (3).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/7f937c27-2527-443c-98c8-a2567c649c37)

### SRU, MRU, HRU filters

These filters are working fine but the decimal values are not allowed even though there values in the table are in decimal.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/72db6517-0a79-4e69-b21a-06b0120d78d1)

and the error message is also not accurate when a decimal value is entered `This field must be a number larger than 0.`

### GPU

GPU filters are working but they're too strict, for example in the `GPU's vendor name` if i entered `amd` nothing will be returned and i must type `Advanced Micro Devices` for it to return something.

The same issue is present in the `GPU's device name` if i searched with `Radeon RX 7900 XT` it will not return anything even though that's the correct model of the gpu and i have to enter it the exact same way as written in the details for it to be returned.

[TF DASHBOARD (4).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/14bac262-6cd6-4462-b707-0d1191940eb9)

I think it would be a better experience for both of these filters if it could match the searched text with any part/sub-string of the one in the details and it doesn't have to be the exact string for it to work.

**Comment by Mahmoud-Emad** [comment]
- The CRU filter implementation in the Swagger UI was reported as an issue in [this link](https://github.com/threefoldtech/tfgrid-sdk-go/issues/249#issuecomment-1651652637). It needs to be addressed and fixed.

- The implementation of the GPU device and vendor name can be found in [this pull request](https://github.com/threefoldtech/tfgrid-sdk-go/pull/259). Make sure to review and test it thoroughly before merging.

- Regarding filtering by a decimal point, caution should be exercised as the grid proxy will return a 400-Bad request when encountering the dot. Even rounding the value before sending it will result in the same as without a decimal point.

**Comment by mohamedamer453** [comment]
> * Regarding filtering by a decimal point, caution should be exercised as the grid proxy will return a 400-Bad request when encountering the dot. Even rounding the value before sending it will result in the same as without a decimal point.

An issue was created for decimal support from the gridproxy https://github.com/threefoldtech/tfgrid-sdk-go/issues/261, but for now leaving it as is should be ok.

however the message that appears when the user enters a decimal value should be updated since now it mentions that the entered value should be greater than 0.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/31609ee6-765f-4e6b-8fa8-2bb8c702ca81)

**Comment by Mahmoud-Emad** [comment]
The updates should be at the development now

**Comment by mohamedamer453** [comment]
GPU filters are now less strict and allow searching with a sub-string instead of the full string.

### GPU's device name

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4964158c-924b-4e68-bb73-4a0dff8057b8)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/c8f11d11-f50b-4c79-9c29-a9de27c66f17)

### GPU's vendor name

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/3dce8d3b-2a26-4065-a083-9e3ed10ea01b)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/9f669ffe-499f-4377-b18f-efdba282256c)

**Comment by mohamedamer453** [comment]
The other 2 issues regarding the `cru` filter and the error message are not released yet on devnet.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The cru filter was fixed.

[TF DASHBOARD (6).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a7635204-c3c2-4085-9665-7dad56dcf461)

and the fields now accept decimal values without any issues.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/e5df9de8-d1fb-4dd2-9825-a101ae5feff1)
