### ISSUE TITLE
Edit cost message to include GPU

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#750]
The cost message does not indicate that extra fees will be added if GPU is selected.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/13702777-9b91-469e-8f53-776c20183b84)

**Comment by Mahmoud-Emad** [comment]
Update the message of the calculator price

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/e10cd6d9-f5a0-4423-8d4b-5b80e80dbbfb)

will continue on it next Sunday, the code needs some refactor, also there is one case that want to be covered

**Comment by Mahmoud-Emad** [comment]
Waiting Zinab's code to be merged to continue work on this

**Comment by mohamedamer453** [comment]
Verified on devnet.

The Pricing message is now the same as the one for dedicated nodes since any node with gpu is dedicated. and the message mentions that no fees for this deployment will be added since the cost is already included in the rent contract.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/3a9cea2d-9474-4e9c-85d8-657f5d2aca19)
