### ISSUE TITLE
Edit price message to include discount for certified & dedicated nodes

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#764]
According to [this](https://github.com/threefoldtech/home/issues/1442), calculated prices should include the discount for dedicated & certified nodes.

**Comment by zaelgohary** [comment]
Blocked on [this](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/757).

**Comment by mohamedamer453** [comment]
Verified on devnet.

For the same deployment.

- Without any filters

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/c5b31907-e6d9-46e1-9136-5a056879a690)

- With `Certified` filter the cost in tft and usd is increased by 25%

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ddb45d18-2b51-4a04-b601-95cc78616353)

- With `Dedicated` filter it hides the cost and mentions that no fess will be added since the cost is already included in the rent contract

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/72167605-08cb-4433-92fa-ad17d87b0a1b)
