### ISSUE TITLE
(Mainnet Verification) Check storage pools before deploying VMs

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#864]
- on the grid client, add the check before sending the deployment to the node
- on the playground, use it instead of the ping nodes to check if the disk size can fit on the storage pools

**Comment by 0oM4R** [comment]
__Update__: not that much progress now i can get the storage pool and the deploying disks to the checkStorage function,
now I'm trying to implement the search logic to fit all disks in side the available pool

**Comment by 0oM4R** [comment]
implemented the search logic; need to sync whit zos team to know how zos distribute the disks on the storage pool

**Comment by 0oM4R** [comment]
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/886
 will sort disks before deployment

**Comment by 0oM4R** [comment]
__Update__:
update pr #897  to check hdd disks and check multiple rootfs disks <in case of multiple vms>

**Comment by A-Harby** [comment]
@0oM4R Small comment; using `Checking if the disks will fit in the node's storage pools...`  maybe isn't the best statement to be used for the end user, Isn't clear what is being checked and will cause a confusion if the check fails (user would have no idea what caused the error or how to fix it).

**Comment by 0oM4R** [comment]
@A-Harby Can you suggest something please?

**Comment by A-Harby** [comment]
> @A-Harby Can you suggest something please?

I think our main focus should be on improving the statement provided when the check fails, it's better to tell the user what to do rather than what failed, so giving him statements like lower the disks size or try other node (maybe if possible you can clarify which disk size was larger than node's disk and print sizes of them). 

And maybe for the check itself it could be 'Checking the compatibility between the disks and the collection of the disks within the node...' , But if we add the part above the current check would be also be good enough.

**Comment by A-Harby** [comment]
Verified, mainnet 2.1.0.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/621cbd16-d302-44ed-86ef-4b04f86126c1)
