### ISSUE TITLE
Can't create new twin on testnet

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#974]
### Description
Testnet 2.1.0-rc8

After generating new accounting mnemonics and accept term and conditions, can't login using the generated mnemonics giving me the error `Couldn't find a user for the provided mnemonic on test network.`

### Logs/Alerts

[Untitled_ Aug 13 2023 3_27 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/903d109a-ecdd-4495-bcba-ff68392eef8b)

**Comment by AhmedHanafy725** [comment]
the issue is found and fixed already [here](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/936/files#diff-27ad5a3a40a58ada2eaf4d72aae09bcc506bb2ec69d95ec258d2479236b6ad90R68), the account was created on devnet.

and for the error message that change after enter the mnemonic twice  also fixed [here](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/976)
