### ISSUE TITLE
GPU Cards label is displayed on deployment details without choosing GPU option

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#983]
### Description
Testnet 2.1.0-rc8.

I deployed a FullVM without a GPU, however the GPU Cards label is displayed and continues to load.
It keeps loading however I done closing and opening deployment details or refreshing the page.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4895815d-1915-41c3-901b-5a2c87ae1ed2)

**Comment by A-Harby** [comment]
It's also displayed on other solution despite that GPU is only available on FullVm.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2f45ef57-4d4f-4387-94fe-7fccfa6079fa)

**Comment by zaelgohary** [comment]
The issue is already fixed on [here](https://github.com/threefoldtech/tfgrid-sdk-ts/commit/51ddbf8200e99ca170eb252be48ae5ebd03058d3#diff-63107baf3aba9a0effc57b33a2cb46755a8ca6f8c51106b7dfedff25d0dfe240R222) devnet as seen below.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/3b4ca053-6a73-4cf8-9b4d-07dc084b8732)

**Comment by A-Harby** [comment]
Verified, Testnet 2.1.0-rc10.

Issue is fixed and GPU Card label is removed.

MicroVM.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1956bac2-20f9-4635-9260-5649f7e9c50c)
FullVM.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0b49598b-8197-4482-be20-5e3798012497)
Owncloud.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/57c65b80-a92a-41ff-97d8-4c35c5c40c5f)
